using Postgrest.Attributes;
using Postgrest.Models;

namespace PersonalFinanceTracker.Domain.Entities;

[Table("transactions")]
public class Transaction : BaseModel
{
    [PrimaryKey("id", false)] // false = not auto-generated by the client (auto-generated by DB usually, or we supply Guid)
    public Guid Id { get; set; }

    [Column("title")]
    public string Title { get; set; } = string.Empty;

    [Column("amount")]
    public decimal Amount { get; set; }

    [Column("user_id")]
    public Guid UserId { get; set; }
    
    [Column("category_id")]
    public Guid? CategoryId { get; set; }

    [Column("transaction_date")]
    public DateTime TransactionDate { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }
}
